### ISSUE TITLE
Popover Content -> View

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#103]
Intuitively, I tried to change the `Popover.Content` with `View` what currently seems only partially working, because Popover has his own styling mechanism e.g. for border radius.

```
<Popover.Content>
    <View borderColor="primary" borderRadius="small" height="100px">
        <Text>Test</Text>
    </View>
</Popover.Content>
```
![image](https://user-images.githubusercontent.com/87228994/210967395-6fb648c3-8147-4936-b2ef-5392cb2298c9.png)

**Comment by blvdmitry** [comment]
That's probably a good case for us to expose our headless part of the popover that doesn't bring any visual styles for the content area

**Comment by blvdmitry** [comment]
I've been thinking about providing a separate set of headless components for a while, but considering that even headless components require some styling (e.g. Popover requires positioning even in libraries like Radix) – I think for now a better approach could be to start covering components with a headless variant. That won't really simplify the adoption by people who want to start with the headless part first but that's also not the main use case we're building this for. 

I think it's better to stay focused on supporting users who got Reshaped for its theming capabilities and utilities that solve styling problems. Otherwise I think people can benefit from using headless libraries directly. 

So I'll start with Popover that will support a headless variant in the next release, which should solve your use case exactly in a way you've tried to solve it:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/887379/215338075-60b8b68b-9efc-4ea0-93b1-19d516508d20.png">
