### ISSUE TITLE
[Android] Dark mode not detected

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#108]
I've activated on my phone dark mode, but the reshaped Website is not identifying it automatically.

I think this would beneficially because it's some sort of implicit showcase for your product, that Reshaped is able to deal with automatic light/dark recognition.

Running Android 12

**Comment by mmailaender** [comment]
Could it be, that Reshaped is currently not supporting out of the Box identifying the System theme? Can't find it in the docs

https://reshaped.so/content/docs/hooks/use-theme
https://reshaped.so/content/docs/utilities/reshaped
https://reshaped.so/content/docs/utilities/theme-provider

**Comment by blvdmitry** [comment]
Yes, it doesn't right now. Supporting it in CSS would mean duplicating the amount of color variable definitions for each theme, so I've done a research of how we can apply it through JS. Currently possible approach is too limiting when you're not applying it on the product yourself, so we're waiting for the user preferences headers support.

More details here: https://blvworkspace.notion.site/Dark-mode-System-color-mode-5e69183191ab4f768b82fa2d3b3614b8

However I think it might be a good idea to:
- Link to an example for people who want to implement it on the product side
- Implement it for the docs

**Comment by mmailaender** [comment]
Could you not solve it with the CSS `prefers-color-schema` media feature without duplicating the variables?  https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

```
@media (prefers-color-scheme: dark) {
  .color-schema {
    --rs-color-background-neutral: black;
  }
}

@media (prefers-color-scheme: light) {
  .color-schema {
    --rs-color-background-neutral: white;
  }
}
```

**Comment by blvdmitry** [comment]
Not completely, only the CSS part of it. There are 3 steps:
1. Just use prefers-color-scheme. All products using Reshaped will get the OS system applied to the web application. It's good for some apps, not for others. There are cases when products might want to switch the themes manually or only be available in one theme.
2. Support both. That means that we'll need to duplicate the variables to be available inside the prefers-color-scheme and separately with just a selector. It's possible to solve this either by providing 2 different css files for each theme to let users pick which approach they need or maybe by working with selectors differently and might have some limitations for products who want to start with a system color mode and then switch to a user defined one.
3. 1 and 2 are solving it on the css level but there is also a JSX part of the problem there. For example, if you want to display a color mode switch / pass color mode to a 3rd party widget, your useTheme hook should know which color mode it is. If we say we only need this on the client side, then we don't care much about solving 1 and 2 either because you can just access the JS api for the prefers-color-scheme. But for SSR this won't work and you will end up with a flash of styled content having wrong color mode applied.

So in the end the only solution that gets us much closer for solving SSR is to inject a synchronous script in the document head, which will be executed on the client but before any html was rendered. It still lacks some functionality because it's desynchronised with the React hydration and header for user preference hints are meant to solve that.

Meanwhile, it's possible to work with a common trick, applying visibility: hidden to the whole page during SSR, and remove it on mount after the color mode is already accessible to the React code

**Comment by mmailaender** [comment]
Oh, thx for clarification - not thought that it's that complex in the background. 😅

**Comment by blvdmitry** [comment]
Added docs on working with the system color mode for now and added system color mode support to the docs website as well (for the first time opened)
