### ISSUE TITLE
Benefit of FormControl.Label & .Helper? 

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#110]
Why not simply using <Text> where
1. I have more flexibility in Styling
2. I would reuse an already existing component instead of having a new one? 

The benefit that I see in FormControl is .Error and .Success

https://reshaped.so/content/docs/utilities/form-control

**Comment by blvdmitry** [comment]
Main reason is accessibility since it automatically links it to the field with aria attributes. I can add more information about it to the docs. Second one is still consistency across the board but I guess you have a case where you want them to look differently?

One option is available right now is to just pass another component inside. That does mean that there will be an additional wrapper so I think I can add support for the render props approach if that helps in your case

**Comment by mmailaender** [comment]
You mean supporting wrapping <Text> inside?

```
<FormControl>
  <FormControl.Label><Text>Favorite fruit:</Text></FormControl.Label>
  <TextField name="fruit" />
  <FormControl.Helper>Melons are berries</FormControl.Helper>
</FormControl> 
```

**Comment by blvdmitry** [comment]
Yes, right now your code snippet should already work but that adds another html element to the markup. 
Supporting render props like in Hidden component could help developers optimise that:
```
<FormControl.Label>
  {attributes => <Text attributes={attributes}>Favorite fruit:</Text>}
</FormControl.Label>

```
