### ISSUE TITLE
Blur Image

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#118]
It seems currently not possible to blur an Image with https://reshaped.so/content/docs/utilities/image

Are you thinking about keep maintaining it, or should I simply use nextjs image?

**Comment by blvdmitry** [comment]
We thinking keeping the utility since it provides helpful functionality for rendering image fallbacks and event handling. Currently it indeed competes with Next.js in some way because Next image is aiming to to better integrate with their build time and Vercel functionality. If there is an interest in this - I can research an advanced API for using them together but that's likely to be more verbose (maybe render props)

**Comment by blvdmitry** [comment]
I would say for blur – you can just apply it using className right now, seems to work fine with `filter: blur(4px);` 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/887379/213001781-f6fca597-d296-41db-86f4-ad8da349e156.png">

**Comment by mmailaender** [comment]
Understood - I think an interesting step would be to make the `style` prop available for all components to have some fallback for functionality that is outside your current scope.
Yes, I agree that I could assign a class to className, but I really like it to have the style directly in place - makes it easier to understand the logic (At least for me ;) )

**Comment by blvdmitry** [comment]
There is a way to do that with `attributes={{ style }}`

**Comment by blvdmitry** [comment]
I'll close this for now since the original question was resolved
