### ISSUE TITLE
Problem with View and ViewItem columns 

### ISSUE THREAD

**Issue by NadimHallaq** [formaat-design/community#137]
There is a problem with the View and View Item, when creating a grid of 12 columns with direction="row". If I add the divider prop the columns will flex to the bottom rather than remain in 1 row, the only solution I found is to consider the grid an 11 column grid.

`  <Container padding={0}>
        <View width="100%" direction={"row"} divided>
          <View.Item columns={2}></View.Item>
          <View.Item columns={8}></View.Item>
          <View.Item columns={2}></View.Item>
        </View>
      </Container>`

In this code example, the expected behaviour is a grid of 12 column, but when I add the last column (columns=2),  it goes to the bottom, rather than remain horizontal.

This only happens when you add the divided prop.

Let me know if I'm doing something wrong, 

Thanks

**Comment by blvdmitry** [comment]
Thanks. I think that's indeed happening with dividers taking extra 2 px of the space. I think there is an easy fix for this I can ship, since dividers already support a `blank` flag which will make them take no space. I'll let you know once it's ready.

**Comment by blvdmitry** [comment]
Got it working, turned out to be a bit more complicated since the reason was getting 2 additional gaps when dividers are added. Since native gap doesn't handle percentage width (e.g. you can't set 2 columns with width: 50% and also have a gap), I've now added additional css calculations for the case when divided flag is used

<img width="786" alt="image" src="https://user-images.githubusercontent.com/887379/222287947-347d1616-216e-4f70-9579-637ba93734e1.png">

**Comment by blvdmitry** [comment]
@NadimHallaq 1.13.1 is live now

**Comment by NadimHallaq** [comment]
Thank you Dmitry!
