### ISSUE TITLE
Accordion. Chevron icon

### ISSUE THREAD

**Issue by bohdank1995** [formaat-design/community#149]
I'd like to be able to reposition the chevron icon to the start of the Accordion. And also it would be cool if I can change icons e.g. from chevron to plus or any else icon.

**Comment by blvdmitry** [comment]
Hey, sure. I'll add this feature for the next minor release available natively and for now I think you should be able to implement it using a custom trigger: https://reshaped.so/content/docs/utilities/accordion#custom-trigger

**Comment by blvdmitry** [comment]
Adding a new iconPosition prop for the upcoming v2 nightly release: 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/887379/235295799-8930306d-b1f3-434a-9030-7f890ac00ee8.png">

After considering a custom icon support and checking the approaches others are taking – I think it's better to keep it in the scope of using a custom trigger element, since it would also usually require a custom transition effect. So you can use `Actionable` or `MenuItem` and render it with a custom icon and add your own transition effect there
