### ISSUE TITLE
[Feature] Tailwind x0 token

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#153]
Spacing token x0 missing to place elements directly at the border.

![image](https://user-images.githubusercontent.com/87228994/236285038-8750aea9-157a-43d4-abc1-3ef24f2756e0.png)

**Comment by blvdmitry** [comment]
Good point, we don't have it as a token in the theme, but I can add it to the tailwind config on top of the default theme

**Comment by blvdmitry** [comment]
Similar issue that I'm going to handle together with this one: 
black and white colors are not added to the text/bg/border groups

**Comment by blvdmitry** [comment]
Releasing this tomorrow, made it `0` instead of `x0` since there is no x0 token in reshaped and it's just an empty value

<img width="203" alt="image" src="https://user-images.githubusercontent.com/887379/236617693-c1f55bdb-007e-4c2f-afb6-35730086c435.png">
<img width="176" alt="image" src="https://user-images.githubusercontent.com/887379/236617711-6c72dfd1-48f3-4404-b191-189b791243c6.png">
